services:

  kali:
    image: l4rm4nd/kali:latest
    container_name: kali
    hostname: kali
    restart: unless-stopped
    ports:
      - 2222:22/tcp # ssh (optional)
    volumes:
      #- ./kali-volume-data:/root # persist root data
      #- ./wg0.conf:/etc/wireguard/wg0.conf:ro # custom vpn config
      #- ./authorized_keys:/root/.ssh/authorized_keys:ro # custom ssh keys
    cap_add:
      - NET_ADMIN
      - NET_RAW
    tty: true
    stdin_open: true